/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ApprovalReceiverInterface extends Interface {
  getFunction(nameOrSignature: "receiveApproval"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ApprovalReceived"): EventFragment;

  encodeFunctionData(
    functionFragment: "receiveApproval",
    values: [AddressLike, BigNumberish, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "receiveApproval",
    data: BytesLike
  ): Result;
}

export namespace ApprovalReceivedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    token: AddressLike,
    extraData: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    amount: bigint,
    token: string,
    extraData: string
  ];
  export interface OutputObject {
    from: string;
    amount: bigint;
    token: string;
    extraData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ApprovalReceiver extends BaseContract {
  connect(runner?: ContractRunner | null): ApprovalReceiver;
  waitForDeployment(): Promise<this>;

  interface: ApprovalReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  receiveApproval: TypedContractMethod<
    [
      from: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "receiveApproval"
  ): TypedContractMethod<
    [
      from: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ApprovalReceived"
  ): TypedContractEvent<
    ApprovalReceivedEvent.InputTuple,
    ApprovalReceivedEvent.OutputTuple,
    ApprovalReceivedEvent.OutputObject
  >;

  filters: {
    "ApprovalReceived(address,uint256,address,bytes)": TypedContractEvent<
      ApprovalReceivedEvent.InputTuple,
      ApprovalReceivedEvent.OutputTuple,
      ApprovalReceivedEvent.OutputObject
    >;
    ApprovalReceived: TypedContractEvent<
      ApprovalReceivedEvent.InputTuple,
      ApprovalReceivedEvent.OutputTuple,
      ApprovalReceivedEvent.OutputObject
    >;
  };
}
