/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IApproveAndCallReceiver } from "./IApproveAndCallReceiver";
export type { IOracle } from "./IOracle";
export type { IWhitelist } from "./IWhitelist";
