/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWhitelist,
  IWhitelistInterface,
} from "../../../../../artifacts/hardhat-vultisig/contracts/interfaces/IWhitelist";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "checkWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWhitelist__factory {
  static readonly abi = _abi;
  static createInterface(): IWhitelistInterface {
    return new Interface(_abi) as IWhitelistInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IWhitelist {
    return new Contract(address, _abi, runner) as unknown as IWhitelist;
  }
}
